name: CI

on: [push,pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: another one liner
      run: brew update
    - name: Install hyperkit
      run: |
        brew install hyperkit
