name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: step1
      run: sudo apt-get update
    - name: step2
      run: sudo apt-get update
    - name: step3
      run: sudo egrep -c '(vmx|svm)' /proc/cpuinfo || true
    - name: step4
      run: sudo apt-get install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
    - name: step5
      run: curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    - name: step6
      run: sudo install minikube-linux-amd64 /usr/local/bin/minikube
    - name: step7_a
      run: sudo addgroup libvirtd
    - name: step7_a
      run: sudo usermod -a -G libvirtd $(whoami)
    - name: step7_b
      run: sudo adduser `id -un` libvirtd
    - name: step7_c
      run: groups
    - name: step8
      run: minikube start --vm-driver=kvm2 
    - name: step9
      run: minikube status
    - name: step10
      run: minikube kubectl get pods -A
