name: CI

on: [pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: intall minikube
      run: 
        git clone https://github.com/moby/hyperkit
        cd hyperkit && make && cp ./build/hyperkit /usr/local/bin/
        brew update
        brew install minikube
        minikube version
        hyperkit -v
    - name: start
      run: minikube start


