name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install minikube && kvm
      run: |
      sudo apt-get update
      sudo egrep -c '(vmx|svm)' /proc/cpuinfo
      sudo apt-get install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
      curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      sudo install minikube-linux-amd64 /usr/local/bin/minikube
      sudo adduser `id -un` libvirtd
      minikube start --vm-driver=kvm2
      minikube status
      minikube kubectl get pods -A

      
