name: CI

on: [pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: another one liner
      run: brew update
    - name: Install hyperkit
      run: |
        brew install hyperkit
    - name: intall minikube
      run: brew install minikube
    - name: versions
      run: |
        minikubbe version
        hyperkit -v
    - name: start
      run: minikube start


